import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Featured from "../components/Featured";
import ProductList from "../components/ProductList";
import styles from "../styles/Home.module.css";
import Swal from "sweetalert2";
import { useDispatch } from "react-redux";
import { update } from "../redux/cartSlice";

export default function Home({ productList, admin }) {
  // const Alert = () => {
  //   Swal.fire({
  //     title: "Enter your Good Name",
  //     input: "text",
  //     inputAttributes: {
  //       autocapitalize: "off",
  //     },
  //     // showCancelButton: true,
  //     confirmButtonText: "Submit",
  //     showLoaderOnConfirm: true,
  //     preConfirm: (e) => {
  //       setCustomer(e);
  //     },
  //     allowOutsideClick: () => !Swal.isLoading(),
  //   });
  // };
  // dispatch(update({ customer }));
  return (
    <div className={styles.container}>
      <Head>
        <title>TiffinTreat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/logo.png" />
      </Head>
      <Featured />
      <ProductList productList={productList} />
    </div>
  );
}
export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }

  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      productList: res.data,
      admin,
    },
  };
};
