import React from "react";
import styles from "../styles/donate.module.css";
import Image from "next/image";
import Head from "next/head";

export default function plans() {
    return (
        <div>
            <Head>
                <title>TiffinTreat</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/image/logo.png" />
            </Head>
            <div className={styles.body}>
                <div className={styles.imgContainer} >
                    <img src="/image/menu.png" alt="" className={styles.imgC} />
                    {/* <Image src="/image/menu.png" layout="fill" objectFit="contain" className={styles.imgC} /> */}
                </div>
            </div>
        </div>
    );
}
